# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Costgraph < Formula
  desc "Command line companion for CostGraph"
  homepage "https://costgraph.baselinehq.cloud/"
  version "0.5.0"

  on_macos do
    url "https://setup.costgraph.ai/costgraph-cli/0.5.0/costgraph-cli_darwin_all.tar.gz"
    sha256 "2707b8b4930fb3d7485fcc7e89591a748f9397ac56229f7b8e19e8af70e49a85"

    define_method(:install) do
      bin.install "costgraph"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://setup.costgraph.ai/costgraph-cli/0.5.0/costgraph-cli_linux_amd64.tar.gz"
      sha256 "97e9ca7dfdd2f8fad294cbec747146ec296f26b71b5f435ed13a18412c026156"
      define_method(:install) do
        bin.install "costgraph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://setup.costgraph.ai/costgraph-cli/0.5.0/costgraph-cli_linux_arm64.tar.gz"
      sha256 "9a71600123307a521b7cc8d3123ed31eb7b8bb01e64c43041778d2e2be5183e2"
      define_method(:install) do
        bin.install "costgraph"
      end
    end
  end
end
