# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CostgraphAgent < Formula
  desc "VM agent for Costgraph"
  homepage "https://costgraph.baselinehq.cloud/"
  version "0.0.29"

  on_macos do
    if Hardware::CPU.intel?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.29/costgraph-agent_v0.0.29_darwin_amd64.tar.gz"
      sha256 "1c780dd8f6f72a6e2a0dd0ad1f8e25686be7a0554fc727d643fe8bbddfc6c3a3"

      def install
        bin.install "costgraph-agent"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.29/costgraph-agent_v0.0.29_darwin_arm64.tar.gz"
      sha256 "65f679efe4afdd60fdf68f3080534fcaa35caeea816aa70b3fe719ab9e05f76a"

      def install
        bin.install "costgraph-agent"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.29/costgraph-agent_v0.0.29_linux_amd64.tar.gz"
      sha256 "6e9d0a9a3203e1ca1d556443ee4e0279a1745f2409636e17b398dff8e53fe09a"
      def install
        bin.install "costgraph-agent"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.29/costgraph-agent_v0.0.29_linux_arm64.tar.gz"
      sha256 "483630f49ac54db745f2279037c19f33b4c3e3a2dd3cca6b05e98b120db7aa36"
      def install
        bin.install "costgraph-agent"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
  end

  def post_install
    (etc/"costgraph_agent").mkpath
    conf = etc/"costgraph_agent/config.yaml"

    unless conf.exist?
      conf.write <<~EOS
        # Costgraph Agent configuration
        api_key: ""
      EOS
    end
  end

  def caveats
    <<~EOS
      This formula requires additional configuration post-installation.

      Update the configuration file at #{etc}/costgraph_agent/config.yaml. It requires an API key which you can obtain from the Costgraph UI.

      To start the service, run `sudo brew services start #{name}`
    EOS
  end

  service do
    run ["#{opt_bin}/costgraph-agent", "--config", "#{etc}/costgraph_agent/config.yaml"]
    keep_alive true
    log_path "#{var}/log/costgraph_agent.log"
    error_log_path "#{var}/log/costgraph_agent.error.log"
    require_root true
  end

  test do
    assert_predicate("#{opt_bin}/costgraph-agent", :exist?)
  end
end
