# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CostgraphAgent < Formula
  desc "VM agent for Costgraph"
  homepage "https://costgraph.baselinehq.cloud/"
  version "0.0.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.23/costgraph-agent_v0.0.23_darwin_amd64.tar.gz"
      sha256 "eb16fbd7dbcf5ada52a7948183ec6e0f4517717cd8a897d25864ae7bc3a8b62a"

      def install
        bin.install "costgraph"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.23/costgraph-agent_v0.0.23_darwin_arm64.tar.gz"
      sha256 "c8990773b3311a7b0862526a7a9834e56a60dfcff941a8415deb58c1573dbd3f"

      def install
        bin.install "costgraph"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.23/costgraph-agent_v0.0.23_linux_amd64.tar.gz"
      sha256 "2aeda4c8876df9e898b7ac68dae593b090981d71d28c18b6ff1e278634afef30"
      def install
        bin.install "costgraph"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.23/costgraph-agent_v0.0.23_linux_arm64.tar.gz"
      sha256 "bccb5c32f3dbca37d1ee257eb5a1a175962a6a0c67d4b70586b69f2f227dbc00"
      def install
        bin.install "costgraph"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
  end
end
