# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CostgraphAgent < Formula
  desc "VM agent for Costgraph"
  homepage "https://costgraph.baselinehq.cloud/"
  version "0.0.38"

  on_macos do
    if Hardware::CPU.intel?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.38/costgraph-agent_v0.0.38_darwin_amd64.tar.gz"
      sha256 "1bf869f2e67aa99ba12cfc570702a7c2bac0eeb6b4cb380dd7e3229e2f618942"

      def install
        bin.install "costgraph-agent"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.38/costgraph-agent_v0.0.38_darwin_arm64.tar.gz"
      sha256 "e30769338afe5910864ba45d7e85f126fdf5f2030a8ddc4f7385d54a24e31e75"

      def install
        bin.install "costgraph-agent"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.38/costgraph-agent_v0.0.38_linux_amd64.tar.gz"
      sha256 "71519f5c2f73aae90b1d3fcc78735a5f6041875eafe03e68c50dc0cd18bb5767"
      def install
        bin.install "costgraph-agent"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://costgraph-agent-bin.s3.amazonaws.com/v0.0.38/costgraph-agent_v0.0.38_linux_arm64.tar.gz"
      sha256 "1bb4cdb7e979186e7b238e4e19046bffe1bdb8b0c4c301dbc1b641e87854b9a7"
      def install
        bin.install "costgraph-agent"
        if OS.mac?
          if Hardware::CPU.arm?
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_arm64.dylib" => "libdarwin_exporter.dylib"
          else
            lib.install "internal/collectors/darwinexporter/libdarwin_exporter_amd64.dylib" => "libdarwin_exporter.dylib"
          end
        end
      end
    end
  end

  def post_install
    (etc/"costgraph_agent").mkpath
    conf = etc/"costgraph_agent/config.yaml"

    unless conf.exist?
      conf.write <<~EOS
        # Costgraph Agent configuration
        api_key: ""
      EOS
    end
  end

  def caveats
    <<~EOS
      This formula requires additional configuration post-installation.

      Update the configuration file at #{etc}/costgraph_agent/config.yaml. It requires an API key which you can obtain from the Costgraph UI.

      To start the service, run `sudo brew services start #{name}`
    EOS
  end

  service do
    run ["#{opt_bin}/costgraph-agent", "--config", "#{etc}/costgraph_agent/config.yaml"]
    keep_alive true
    log_path "#{var}/log/costgraph_agent.log"
    error_log_path "#{var}/log/costgraph_agent.error.log"
    require_root true
  end

  test do
    assert_predicate("#{opt_bin}/costgraph-agent", :exist?)
  end
end
